services:
  - type: web
    name: pharmaintelscan
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /_stcore/health
    autoDeploy: true
    plan: starter 